version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: touch src/config.json
  test:
    docker:
      - image: circleci/node:12.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn lint
      - run: yarn test
  deploy-dev:
    docker:
      - image: circleci/node:12.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: config=spraoi.dev yarn deploy
  deploy-prod:
    docker:
      - image: circleci/node:12.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: config=spraoi.prod yarn deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-dev:
          requires:
            - test
          filters:
            branches:
              only: development
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only: master
